on:
  push:
    branches:
      - master
    paths:
      - 'game/**'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game to Github
    steps:
    - name: checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    - name: export
      uses: firebelley/godot-export@v3.0.0
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/mono/Godot_v3.4.4-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/mono/Godot_v3.4.4-stable_mono_export_templates.tpz
        godot_template_version: 3.4.4.stable
        relative_project_path: ./game
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }} 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
